repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.0.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
  
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17  
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-myst
    args: ['.']